#Array of 2D cone locations (z = 0)

Header header

geometry_msgs/Point[] blue_cones
float64[4][] blue_covariances
geometry_msgs/Point[] yellow_cones
float64[4][] yellow_covariances
geometry_msgs/Point[] orange_cones
float64[4][] orange_covariances
geometry_msgs/Point[] big_orange_cones
float64[4][] big_orange_covariances
geometry_msgs/Point[] unknown_color_cones
float64[4][] unknown_color_covariances

