#Array of 2D cone locations (z = 0)

Header header

geometry_msgs/Point[] blue_cones
cone_covariance[] blue_covariances
geometry_msgs/Point[] yellow_cones
cone_covariance[] yellow_covariances
geometry_msgs/Point[] orange_cones
cone_covariance[] orange_covariances
geometry_msgs/Point[] big_orange_cones
cone_covariance[] big_orange_covariances
geometry_msgs/Point[] unknown_color_cones
cone_covariance[] unknown_color_covariances

