image: ros:galactic-ros-base-focal

workflow:
  # Only run on ros2 branch and merge requests
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"

variables:
  PROJECT_BASE_DIR: $CI_PROJECT_DIR/src/eufs_msgs

stages:
  - .pre
  - build

setup:
  stage: .pre
  script:
    # Setup file structure
    - mkdir -p $PROJECT_BASE_DIR
    - shopt -s extglob dotglob
    - mv !(src) $PROJECT_BASE_DIR
    - shopt -u extglob dotglob

  variables:
    GIT_STRATEGY: clone
  artifacts:
    expire_in: 1h
    paths:
      - $CI_PROJECT_DIR

build:
  stage: build 
  script:
    # Install ROS package dependencies
    - apt-get update -qq
    - rosdep update -q --rosdistro=$ROS_DISTRO
    - rosdep install -y -q --from-paths src --ignore-src
    - rm -rf /var/lib/apt/lists/*
    
    # Build packages
    - . /opt/ros/$ROS_DISTRO/setup.sh
    - colcon build
  variables:
    GIT_STRATEGY: none
